app/views.py
"""Routes logic."""
from app import db
from app.models import Url
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from hashids import Hashids

url_shortener = Blueprint(
    'url_shortener',
    __name__,
    template_folder='templates',
)

hashids = Hashids(min_length=4, salt=current_app.secret_key)


@url_shortener.route('/', methods=('GET', 'POST'))
def index():  # noqa: WPS210
    """Render index page.

    Returns:
        str.
    """
    if request.method == 'POST':
        url = request.form['url']

        if Url.query.filter(Url.original_url == url).scalar():

            url_data = Url.query.filter(
                Url.original_url == url,
            ).one()
            short_url = request.host_url + hashids.encode(url_data.id)
            return render_template('index.html', short_url=short_url)

        if url:
            url_data = Url(original_url=url)

            db.session.add(url_data)
            db.session.commit()

            url_id = url_data.id
            hashid = hashids.encode(url_id)
            short_url = request.host_url + hashid

            return render_template('index.html', short_url=short_url)

        flash('The URL is required!')
        return redirect(url_for('url_shortener.index'))

    return render_template('index.html', page=1)


@url_shortener.route('/<url_id>')
def url_redirect(url_id: int):
    """Redirect to url.

    Args:
        url_id: shorten url id.

    Returns:
        Response.
    """
    original_id = hashids.decode(url_id)

    if original_id:
        original_id = original_id[0]
        url_data = Url.query.filter(
            Url.id == original_id,
        ).one()

        original_url = url_data.original_url
        url_data.clicks_counter = Url.clicks_counter + 1

        db.session.commit()
        db.session.close()
        return redirect(original_url)
    flash('Invalid URL')
    return redirect(url_for('url_shortener.index'))


@url_shortener.route('/stats/page/<int:page>', methods=['GET'])
def stats(page: int = 1):
    """Render statictic page with pagination.

    Args:
        page: first page.

    Returns:
        str.
    """
    per_page = 5
    urls = Url.query.order_by(Url.id).paginate(page, per_page, error_out=False)
    db.session.close()

    short_urls = {}
    for url in urls.items:

        short_url = request.host_url + hashids.encode(url.id)
        short_urls[url.id] = short_url

    return render_template('stats.html', url=urls, short_urls=short_urls)


@url_shortener.route('/about')
def about():
    """Render about page.

    Returns:
        str.
    """
    return render_template('about.html')

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center mt-3">{% block title %} UrlShortener {% endblock %}</h1>
      <p class="text-center">
          Small application to short and store your URL created using Flask and SQLAlchemy.</br>
      </p>
      <div class="row-cols-2 text-center">
      <a href="https://github.com/emp7yhead/url-shortener" class="btn btn-primary btn-lg">Source Code</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('url_shortener.index')}}">UrlShortener</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
            <div class="navbar-nav">
              <a class="nav-link" href="{{ url_for('url_shortener.stats', page=1)}}">Stats</a>
            </div>
            <div class="navbar-nav">
              <a class="nav-link" href="{{ url_for('url_shortener.about')}}">About</a>
            </div>
          </div>
        </div>
    </nav>
    <div class="container" >
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger mt-3">{{ message }}</div>
        {% endfor %}
        {% block content %} {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
     integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center mt-3">{% block title %} UrlShortener {% endblock %}</h1>
    <form method="post">
    <div class="form-group mb-3">
        <label for="url" class="form-label">Enter your URL here:</label>
        <input type="text" name="url"
               placeholder="URL to shorten" class="form-control"
               value="{{ request.form['url'] }}" autofocus></input>
    </div>

    <div class="d-grid gap-2 col-4 mx-auto">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    </form>

    {% if short_url %}
    <hr>
    <span>{{ short_url }}</span>
    {% endif %}
{% endblock %}

app/templates/stats.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center mt-3">{% block title %} UrlShortener Statistics {% endblock %}</h1>
<table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Short URL</th>
        <th scope="col">Original URL</th>
        <th scope="col">Clicks</th>
        <th scope="col">Creation Date</th>
        </tr>
    </thead>
    <tbody>
        {% for url in url.items %}
            <tr>
                <th scope="row">{{ url.id }}</th>
                <td>
                 {{ short_urls[url.id] }}
                </td>
                <td>{{ url.original_url }}</td>
                <td>{{ url.clicks_counter }}</td>
                <td>{{ url.created }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if url.has_prev %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('url_shortener.stats', page=url.prev_num) }}">
                   &laquo; Previous
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">Previous</a>
            </li>
        {% endif %} 

        {% for page_num in url.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}{% if page_num %}
            {% if url.page == page_num %}
                <li class="page-item active">
                    <a class="page-link" href="{{ url_for('url_shortener.stats', page=page_num) }}">
                      {{ page_num }}
                    </a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('url_shortener.stats', page=page_num) }}">
                      {{ page_num }}
                    </a>
                </li>
            {% endif %}
            {% endif %}   
        {% endfor %}

        {% if url.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('url_shortener.stats', page=url.next_num) }}">
                  Next &raquo;
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">
                  Next
                </a>
            </li>
        {% endif %}
      </li>
    </ul>
</nav>

<p class="text mt-3">
    Showing page {{ url.page }} of {{ url.pages }}
</p>

{% endblock %}